ALTER TABLE `adventure_template` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `graveyard_radius`;
ALTER TABLE `adventure_template` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `doors` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `is_ldon_door`;
ALTER TABLE `doors` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `fishing` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `npc_chance`;
ALTER TABLE `fishing` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `forage` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `chance`;
ALTER TABLE `forage` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `global_loot` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `zone`;
ALTER TABLE `global_loot` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `ground_spawns` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `respawn_timer`;
ALTER TABLE `ground_spawns` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `horses` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `notes`;
ALTER TABLE `horses` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `loottable` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `done`;
ALTER TABLE `loottable` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `lootdrop` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `name`;
ALTER TABLE `lootdrop` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `merchantlist` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `probability`;
ALTER TABLE `merchantlist` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `object` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `display_name`;
ALTER TABLE `object` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `spawn2` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `animation`;
ALTER TABLE `spawn2` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `starting_items` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `slot`;
ALTER TABLE `starting_items` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `start_zones` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `select_rank`;
ALTER TABLE `start_zones` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `titles` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `title_set`;
ALTER TABLE `titles` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `tradeskill_recipe` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `enabled`;
ALTER TABLE `tradeskill_recipe` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `traps` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `undetectable`;
ALTER TABLE `traps` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `tributes` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `isguild`;
ALTER TABLE `tributes` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;
ALTER TABLE `zone` ADD `min_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `npc_max_aggro_dist`;
ALTER TABLE `zone` ADD `max_expansion` TINYINT(4)  UNSIGNED  NOT NULL  DEFAULT '0'  AFTER `min_expansion`;

update zone set min_expansion = 1 where short_name = 'qeynos';
update zone set min_expansion = 1 where short_name = 'qeynos2';
update zone set min_expansion = 1 where short_name = 'qrg';
update zone set min_expansion = 1 where short_name = 'qeytoqrg';
update zone set min_expansion = 1 where short_name = 'highpass';
update zone set min_expansion = 1 where short_name = 'highkeep';
update zone set min_expansion = 1 where short_name = 'freportn';
update zone set min_expansion = 1 where short_name = 'freportw';
update zone set min_expansion = 1 where short_name = 'freporte';
update zone set min_expansion = 1 where short_name = 'runnyeye';
update zone set min_expansion = 1 where short_name = 'qey2hh1';
update zone set min_expansion = 1 where short_name = 'northkarana';
update zone set min_expansion = 1 where short_name = 'southkarana';
update zone set min_expansion = 1 where short_name = 'eastkarana';
update zone set min_expansion = 1 where short_name = 'beholder';
update zone set min_expansion = 1 where short_name = 'blackburrow';
update zone set min_expansion = 1 where short_name = 'paw';
update zone set min_expansion = 1 where short_name = 'rivervale';
update zone set min_expansion = 1 where short_name = 'kithicor';
update zone set min_expansion = 1 where short_name = 'commons';
update zone set min_expansion = 1 where short_name = 'ecommons';
update zone set min_expansion = 1 where short_name = 'erudnint';
update zone set min_expansion = 1 where short_name = 'erudnext';
update zone set min_expansion = 1 where short_name = 'nektulos';
update zone set min_expansion = 1 where short_name = 'nektulos';
update zone set min_expansion = 1 where short_name = 'cshome';
update zone set min_expansion = 1 where short_name = 'lavastorm';
update zone set min_expansion = 1 where short_name = 'halas';
update zone set min_expansion = 1 where short_name = 'everfrost';
update zone set min_expansion = 1 where short_name = 'soldunga';
update zone set min_expansion = 1 where short_name = 'soldungb';
update zone set min_expansion = 1 where short_name = 'misty';
update zone set min_expansion = 1 where short_name = 'nro';
update zone set min_expansion = 1 where short_name = 'sro';
update zone set min_expansion = 1 where short_name = 'befallen';
update zone set min_expansion = 1 where short_name = 'oasis';
update zone set min_expansion = 1 where short_name = 'tox';
update zone set min_expansion = 1 where short_name = 'hole';
update zone set min_expansion = 1 where short_name = 'neriaka';
update zone set min_expansion = 1 where short_name = 'neriakb';
update zone set min_expansion = 1 where short_name = 'neriakc';
update zone set min_expansion = 1 where short_name = 'najena';
update zone set min_expansion = 1 where short_name = 'qcat';
update zone set min_expansion = 1 where short_name = 'innothule';
update zone set min_expansion = 1 where short_name = 'feerrott';
update zone set min_expansion = 1 where short_name = 'cazicthule';
update zone set min_expansion = 1 where short_name = 'oggok';
update zone set min_expansion = 1 where short_name = 'rathemtn';
update zone set min_expansion = 1 where short_name = 'lakerathe';
update zone set min_expansion = 1 where short_name = 'grobb';
update zone set min_expansion = 1 where short_name = 'gfaydark';
update zone set min_expansion = 1 where short_name = 'akanon';
update zone set min_expansion = 1 where short_name = 'steamfont';
update zone set min_expansion = 1 where short_name = 'lfaydark';
update zone set min_expansion = 1 where short_name = 'crushbone';
update zone set min_expansion = 1 where short_name = 'mistmoore';
update zone set min_expansion = 1 where short_name = 'kaladima';
update zone set min_expansion = 1 where short_name = 'felwithea';
update zone set min_expansion = 1 where short_name = 'felwitheb';
update zone set min_expansion = 1 where short_name = 'unrest';
update zone set min_expansion = 1 where short_name = 'kedge';
update zone set min_expansion = 1 where short_name = 'guktop';
update zone set min_expansion = 1 where short_name = 'gukbottom';
update zone set min_expansion = 1 where short_name = 'kaladimb';
update zone set min_expansion = 1 where short_name = 'butcher';
update zone set min_expansion = 1 where short_name = 'oot';
update zone set min_expansion = 1 where short_name = 'cauldron';
update zone set min_expansion = 1 where short_name = 'airplane';
update zone set min_expansion = 1 where short_name = 'fearplane';
update zone set min_expansion = 1 where short_name = 'permafrost';
update zone set min_expansion = 1 where short_name = 'kerraridge';
update zone set min_expansion = 1 where short_name = 'paineel';
update zone set min_expansion = 1 where short_name = 'hateplane';
update zone set min_expansion = 1 where short_name = 'arena';
update zone set min_expansion = 1 where short_name = 'hateplaneb';

update zone set min_expansion = 1 where short_name = 'fhalls';
update zone set min_expansion = 1 where short_name = 'tutoriala';
update zone set min_expansion = 1 where short_name = 'tutorialb';
update zone set min_expansion = 1 where short_name = 'jaggedpine';
update zone set min_expansion = 1 where short_name = 'nedaria';
update zone set min_expansion = 1 where short_name = 'arena2';
update zone set min_expansion = 1 where short_name = 'shadowrest';

update zone set min_expansion = 2 where short_name = 'fieldofbone';
update zone set min_expansion = 2 where short_name = 'warslikswood';
update zone set min_expansion = 2 where short_name = 'soltemple';
update zone set min_expansion = 2 where short_name = 'droga';
update zone set min_expansion = 2 where short_name = 'cabwest';
update zone set min_expansion = 2 where short_name = 'swampofnohope';
update zone set min_expansion = 2 where short_name = 'firiona';
update zone set min_expansion = 2 where short_name = 'lakeofillomen';
update zone set min_expansion = 2 where short_name = 'dreadlands';
update zone set min_expansion = 2 where short_name = 'burningwood';
update zone set min_expansion = 2 where short_name = 'kaesora';
update zone set min_expansion = 2 where short_name = 'sebilis';
update zone set min_expansion = 2 where short_name = 'citymist';
update zone set min_expansion = 2 where short_name = 'skyfire';
update zone set min_expansion = 2 where short_name = 'frontiermtns';
update zone set min_expansion = 2 where short_name = 'overthere';
update zone set min_expansion = 2 where short_name = 'emeraldjungle';
update zone set min_expansion = 2 where short_name = 'trakanon';
update zone set min_expansion = 2 where short_name = 'timorous';
update zone set min_expansion = 2 where short_name = 'kurn';
update zone set min_expansion = 2 where short_name = 'erudsxing';
update zone set min_expansion = 2 where short_name = 'stonebrunt';
update zone set min_expansion = 2 where short_name = 'warrens';
update zone set min_expansion = 2 where short_name = 'karnor';
update zone set min_expansion = 2 where short_name = 'chardok';
update zone set min_expansion = 2 where short_name = 'dalnir';
update zone set min_expansion = 2 where short_name = 'charasis';
update zone set min_expansion = 2 where short_name = 'cabeast';
update zone set min_expansion = 2 where short_name = 'nurga';
update zone set min_expansion = 2 where short_name = 'veeshan';
update zone set min_expansion = 2 where short_name = 'veksar';

update zone set min_expansion = 3 where short_name = 'iceclad';
update zone set min_expansion = 3 where short_name = 'frozenshadow';
update zone set min_expansion = 3 where short_name = 'velketor';
update zone set min_expansion = 3 where short_name = 'kael';
update zone set min_expansion = 3 where short_name = 'skyshrine';
update zone set min_expansion = 3 where short_name = 'thurgadina';
update zone set min_expansion = 3 where short_name = 'eastwastes';
update zone set min_expansion = 3 where short_name = 'cobaltscar';
update zone set min_expansion = 3 where short_name = 'greatdivide';
update zone set min_expansion = 3 where short_name = 'wakening';
update zone set min_expansion = 3 where short_name = 'westwastes';
update zone set min_expansion = 3 where short_name = 'crystal';
update zone set min_expansion = 3 where short_name = 'necropolis';
update zone set min_expansion = 3 where short_name = 'templeveeshan';
update zone set min_expansion = 3 where short_name = 'sirens';
update zone set min_expansion = 3 where short_name = 'mischiefplane';
update zone set min_expansion = 3 where short_name = 'growthplane';
update zone set min_expansion = 3 where short_name = 'sleeper';
update zone set min_expansion = 3 where short_name = 'thurgadinb';

update zone set min_expansion = 4 where short_name = 'shadowhaven';
update zone set min_expansion = 4 where short_name = 'bazaar';
update zone set min_expansion = 4 where short_name = 'nexus';
update zone set min_expansion = 4 where short_name = 'echo';
update zone set min_expansion = 4 where short_name = 'acrylia';
update zone set min_expansion = 4 where short_name = 'sharvahl';
update zone set min_expansion = 4 where short_name = 'paludal';
update zone set min_expansion = 4 where short_name = 'fungusgrove';
update zone set min_expansion = 4 where short_name = 'vexthal';
update zone set min_expansion = 4 where short_name = 'sseru';
update zone set min_expansion = 4 where short_name = 'katta';
update zone set min_expansion = 4 where short_name = 'netherbian';
update zone set min_expansion = 4 where short_name = 'ssratemple';
update zone set min_expansion = 4 where short_name = 'griegsend';
update zone set min_expansion = 4 where short_name = 'thedeep';
update zone set min_expansion = 4 where short_name = 'shadeweaver';
update zone set min_expansion = 4 where short_name = 'hollowshade';
update zone set min_expansion = 4 where short_name = 'grimling';
update zone set min_expansion = 4 where short_name = 'mseru';
update zone set min_expansion = 4 where short_name = 'letalis';
update zone set min_expansion = 4 where short_name = 'twilight';
update zone set min_expansion = 4 where short_name = 'thegrey';
update zone set min_expansion = 4 where short_name = 'tenebrous';
update zone set min_expansion = 4 where short_name = 'maiden';
update zone set min_expansion = 4 where short_name = 'dawnshroud';
update zone set min_expansion = 4 where short_name = 'scarlet';
update zone set min_expansion = 4 where short_name = 'umbral';
update zone set min_expansion = 4 where short_name = 'akheva';

update zone set min_expansion = 5 where short_name = 'codecay';
update zone set min_expansion = 5 where short_name = 'pojustice';
update zone set min_expansion = 5 where short_name = 'poknowledge';
update zone set min_expansion = 5 where short_name = 'potranquility';
update zone set min_expansion = 5 where short_name = 'ponightmare';
update zone set min_expansion = 5 where short_name = 'podisease';
update zone set min_expansion = 5 where short_name = 'poinnovation';
update zone set min_expansion = 5 where short_name = 'potorment';
update zone set min_expansion = 5 where short_name = 'povalor';
update zone set min_expansion = 5 where short_name = 'bothunder';
update zone set min_expansion = 5 where short_name = 'postorms';
update zone set min_expansion = 5 where short_name = 'hohonora';
update zone set min_expansion = 5 where short_name = 'solrotower';
update zone set min_expansion = 5 where short_name = 'powar';
update zone set min_expansion = 5 where short_name = 'potactics';
update zone set min_expansion = 5 where short_name = 'poair';
update zone set min_expansion = 5 where short_name = 'powater';
update zone set min_expansion = 5 where short_name = 'pofire';
update zone set min_expansion = 5 where short_name = 'poeartha';
update zone set min_expansion = 5 where short_name = 'potimea';
update zone set min_expansion = 5 where short_name = 'hohonorb';
update zone set min_expansion = 5 where short_name = 'nightmareb';
update zone set min_expansion = 5 where short_name = 'poearthb';
update zone set min_expansion = 5 where short_name = 'potimeb';

update zone set min_expansion = 6 where short_name = 'gunthak';
update zone set min_expansion = 6 where short_name = 'dulak';
update zone set min_expansion = 6 where short_name = 'torgiran';
update zone set min_expansion = 6 where short_name = 'nadox';
update zone set min_expansion = 6 where short_name = 'hatesfury';
update zone set min_expansion = 6 where short_name = 'chardokb';
update zone set min_expansion = 6 where short_name = 'soldungc';

update zone set min_expansion = 7 where short_name = 'guka';
update zone set min_expansion = 7 where short_name = 'ruja';
update zone set min_expansion = 7 where short_name = 'taka';
update zone set min_expansion = 7 where short_name = 'mira';
update zone set min_expansion = 7 where short_name = 'mmca';
update zone set min_expansion = 7 where short_name = 'gukb';
update zone set min_expansion = 7 where short_name = 'rujb';
update zone set min_expansion = 7 where short_name = 'takb';
update zone set min_expansion = 7 where short_name = 'mirb';
update zone set min_expansion = 7 where short_name = 'mmcb';
update zone set min_expansion = 7 where short_name = 'gukc';
update zone set min_expansion = 7 where short_name = 'rujc';
update zone set min_expansion = 7 where short_name = 'takc';
update zone set min_expansion = 7 where short_name = 'mirc';
update zone set min_expansion = 7 where short_name = 'mmcc';
update zone set min_expansion = 7 where short_name = 'gukd';
update zone set min_expansion = 7 where short_name = 'rujd';
update zone set min_expansion = 7 where short_name = 'takd';
update zone set min_expansion = 7 where short_name = 'mird';
update zone set min_expansion = 7 where short_name = 'mmcd';
update zone set min_expansion = 7 where short_name = 'guke';
update zone set min_expansion = 7 where short_name = 'ruje';
update zone set min_expansion = 7 where short_name = 'take';
update zone set min_expansion = 7 where short_name = 'mire';
update zone set min_expansion = 7 where short_name = 'mmce';
update zone set min_expansion = 7 where short_name = 'gukf';
update zone set min_expansion = 7 where short_name = 'rujf';
update zone set min_expansion = 7 where short_name = 'takf';
update zone set min_expansion = 7 where short_name = 'mirf';
update zone set min_expansion = 7 where short_name = 'mmcf';
update zone set min_expansion = 7 where short_name = 'gukg';
update zone set min_expansion = 7 where short_name = 'rujg';
update zone set min_expansion = 7 where short_name = 'takg';
update zone set min_expansion = 7 where short_name = 'mirg';
update zone set min_expansion = 7 where short_name = 'mmcg';
update zone set min_expansion = 7 where short_name = 'gukh';
update zone set min_expansion = 7 where short_name = 'rujh';
update zone set min_expansion = 7 where short_name = 'takh';
update zone set min_expansion = 7 where short_name = 'mirh';
update zone set min_expansion = 7 where short_name = 'mmch';
update zone set min_expansion = 7 where short_name = 'ruji';
update zone set min_expansion = 7 where short_name = 'taki';
update zone set min_expansion = 7 where short_name = 'miri';
update zone set min_expansion = 7 where short_name = 'mmci';
update zone set min_expansion = 7 where short_name = 'rujj';
update zone set min_expansion = 7 where short_name = 'takj';
update zone set min_expansion = 7 where short_name = 'mirj';
update zone set min_expansion = 7 where short_name = 'mmcj';

update zone set min_expansion = 8 where short_name = 'abysmal';
update zone set min_expansion = 8 where short_name = 'natimbi';
update zone set min_expansion = 8 where short_name = 'qinimi';
update zone set min_expansion = 8 where short_name = 'riwwi';
update zone set min_expansion = 8 where short_name = 'barindu';
update zone set min_expansion = 8 where short_name = 'ferubi';
update zone set min_expansion = 8 where short_name = 'snpool';
update zone set min_expansion = 8 where short_name = 'snlair';
update zone set min_expansion = 8 where short_name = 'snplant';
update zone set min_expansion = 8 where short_name = 'sncrematory';
update zone set min_expansion = 8 where short_name = 'tipt';
update zone set min_expansion = 8 where short_name = 'vxed';
update zone set min_expansion = 8 where short_name = 'yxtta';
update zone set min_expansion = 8 where short_name = 'uqua';
update zone set min_expansion = 8 where short_name = 'kodtaz';
update zone set min_expansion = 8 where short_name = 'ikkinz';
update zone set min_expansion = 8 where short_name = 'qvic';
update zone set min_expansion = 8 where short_name = 'inktuta';
update zone set min_expansion = 8 where short_name = 'txevu';
update zone set min_expansion = 8 where short_name = 'tacvi';
update zone set min_expansion = 8 where short_name = 'qvicb';

update zone set min_expansion = 9 where short_name = 'wallofslaughter';
update zone set min_expansion = 9 where short_name = 'bloodfields';
update zone set min_expansion = 9 where short_name = 'draniksscar';
update zone set min_expansion = 9 where short_name = 'causeway';
update zone set min_expansion = 9 where short_name = 'chambersa';
update zone set min_expansion = 9 where short_name = 'chambersb';
update zone set min_expansion = 9 where short_name = 'chambersc';
update zone set min_expansion = 9 where short_name = 'chambersd';
update zone set min_expansion = 9 where short_name = 'chamberse';
update zone set min_expansion = 9 where short_name = 'chambersf';
update zone set min_expansion = 9 where short_name = 'provinggrounds';
update zone set min_expansion = 9 where short_name = 'anguish';
update zone set min_expansion = 9 where short_name = 'dranikhollowsa';
update zone set min_expansion = 9 where short_name = 'dranikhollowsb';
update zone set min_expansion = 9 where short_name = 'dranikhollowsc';
update zone set min_expansion = 9 where short_name = 'dranikcatacombsa';
update zone set min_expansion = 9 where short_name = 'dranikcatacombsb';
update zone set min_expansion = 9 where short_name = 'dranikcatacombsc';
update zone set min_expansion = 9 where short_name = 'draniksewersa';
update zone set min_expansion = 9 where short_name = 'draniksewersb';
update zone set min_expansion = 9 where short_name = 'draniksewersc';
update zone set min_expansion = 9 where short_name = 'riftseekers';
update zone set min_expansion = 9 where short_name = 'harbingers';
update zone set min_expansion = 9 where short_name = 'dranik';

update zone set min_expansion = 10 where short_name = 'broodlands';
update zone set min_expansion = 10 where short_name = 'stillmoona';
update zone set min_expansion = 10 where short_name = 'stillmoonb';
update zone set min_expansion = 10 where short_name = 'thundercrest';
update zone set min_expansion = 10 where short_name = 'delvea';
update zone set min_expansion = 10 where short_name = 'delveb';
update zone set min_expansion = 10 where short_name = 'thenest';
update zone set min_expansion = 10 where short_name = 'guildlobby';
update zone set min_expansion = 10 where short_name = 'guildhall';
update zone set min_expansion = 10 where short_name = 'barter';

update zone set min_expansion = 11 where short_name = 'illsalin';
update zone set min_expansion = 11 where short_name = 'illsalina';
update zone set min_expansion = 11 where short_name = 'illsalinb';
update zone set min_expansion = 11 where short_name = 'illsalinc';
update zone set min_expansion = 11 where short_name = 'dreadspire';
update zone set min_expansion = 11 where short_name = 'drachnidhive';
update zone set min_expansion = 11 where short_name = 'drachnidhivea';
update zone set min_expansion = 11 where short_name = 'drachnidhiveb';
update zone set min_expansion = 11 where short_name = 'drachnidhivec';
update zone set min_expansion = 11 where short_name = 'westkorlach';
update zone set min_expansion = 11 where short_name = 'westkorlacha';
update zone set min_expansion = 11 where short_name = 'westkorlachb';
update zone set min_expansion = 11 where short_name = 'westkorlachc';
update zone set min_expansion = 11 where short_name = 'eastkorlach';
update zone set min_expansion = 11 where short_name = 'eastkorlacha';
update zone set min_expansion = 11 where short_name = 'shadowspine';
update zone set min_expansion = 11 where short_name = 'corathus';
update zone set min_expansion = 11 where short_name = 'corathusa';
update zone set min_expansion = 11 where short_name = 'corathusb';
update zone set min_expansion = 11 where short_name = 'nektulosa';

update zone set min_expansion = 12 where short_name = 'arcstone';
update zone set min_expansion = 12 where short_name = 'relic';
update zone set min_expansion = 12 where short_name = 'skylance';
update zone set min_expansion = 12 where short_name = 'devastation';
update zone set min_expansion = 12 where short_name = 'devastationa';
update zone set min_expansion = 12 where short_name = 'rage';
update zone set min_expansion = 12 where short_name = 'ragea';
update zone set min_expansion = 12 where short_name = 'takishruins';
update zone set min_expansion = 12 where short_name = 'takishruinsa';
update zone set min_expansion = 12 where short_name = 'elddar';
update zone set min_expansion = 12 where short_name = 'elddara';
update zone set min_expansion = 12 where short_name = 'theater';
update zone set min_expansion = 12 where short_name = 'theatera';
update zone set min_expansion = 12 where short_name = 'freeporteast';
update zone set min_expansion = 12 where short_name = 'freeportwest';
update zone set min_expansion = 12 where short_name = 'freeportsewers';
update zone set min_expansion = 12 where short_name = 'freeportacademy';
update zone set min_expansion = 12 where short_name = 'freeporttemple';
update zone set min_expansion = 12 where short_name = 'freeportmilitia';
update zone set min_expansion = 12 where short_name = 'freeportarena';
update zone set min_expansion = 12 where short_name = 'freeportcityhall';
update zone set min_expansion = 12 where short_name = 'freeporttheater';
update zone set min_expansion = 12 where short_name = 'freeporthall';
update zone set min_expansion = 12 where short_name = 'northro';
update zone set min_expansion = 12 where short_name = 'southro';

update zone set min_expansion = 13 where short_name = 'crescent';
update zone set min_expansion = 13 where short_name = 'moors';
update zone set min_expansion = 13 where short_name = 'stonehive';
update zone set min_expansion = 13 where short_name = 'mesa';
update zone set min_expansion = 13 where short_name = 'roost';
update zone set min_expansion = 13 where short_name = 'steppes';
update zone set min_expansion = 13 where short_name = 'icefall';
update zone set min_expansion = 13 where short_name = 'valdeholm';
update zone set min_expansion = 13 where short_name = 'frostcrypt';
update zone set min_expansion = 13 where short_name = 'sunderock';
update zone set min_expansion = 13 where short_name = 'vergalid';
update zone set min_expansion = 13 where short_name = 'direwind';
update zone set min_expansion = 13 where short_name = 'ashengate';
update zone set min_expansion = 13 where short_name = 'highpasshold';
update zone set min_expansion = 13 where short_name = 'commonlands';
update zone set min_expansion = 13 where short_name = 'oceanoftears';
update zone set min_expansion = 13 where short_name = 'innothuleb';
update zone set min_expansion = 13 where short_name = 'toxxulia';
update zone set min_expansion = 13 where short_name = 'mistythicket';

update zone set min_expansion = 14 where short_name = 'kattacastrum';
update zone set min_expansion = 14 where short_name = 'thalassius';
update zone set min_expansion = 14 where short_name = 'atiiki';
update zone set min_expansion = 14 where short_name = 'zhisza';
update zone set min_expansion = 14 where short_name = 'silyssar';
update zone set min_expansion = 14 where short_name = 'solteris';
update zone set min_expansion = 14 where short_name = 'barren';
update zone set min_expansion = 14 where short_name = 'buriedsea';
update zone set min_expansion = 14 where short_name = 'jardelshook';
update zone set min_expansion = 14 where short_name = 'monkeyrock';
update zone set min_expansion = 14 where short_name = 'suncrest';
update zone set min_expansion = 14 where short_name = 'deadbone';
update zone set min_expansion = 14 where short_name = 'blacksail';
update zone set min_expansion = 14 where short_name = 'maidensgrave';
update zone set min_expansion = 14 where short_name = 'redfeather';
update zone set min_expansion = 14 where short_name = 'shipmvp';
update zone set min_expansion = 14 where short_name = 'shipmvu';
update zone set min_expansion = 14 where short_name = 'shippvu';
update zone set min_expansion = 14 where short_name = 'shipuvu';
update zone set min_expansion = 14 where short_name = 'shipmvm';

update zone set min_expansion = 15 where short_name = 'mechanotus';
update zone set min_expansion = 15 where short_name = 'mansion';
update zone set min_expansion = 15 where short_name = 'steamfactory';
update zone set min_expansion = 15 where short_name = 'shipworkshop';
update zone set min_expansion = 15 where short_name = 'gyrospireb';
update zone set min_expansion = 15 where short_name = 'gyrospirez';
update zone set min_expansion = 15 where short_name = 'dragonscale';
update zone set min_expansion = 15 where short_name = 'lopingplains';
update zone set min_expansion = 15 where short_name = 'hillsofshade';
update zone set min_expansion = 15 where short_name = 'bloodmoon';
update zone set min_expansion = 15 where short_name = 'crystallos';
update zone set min_expansion = 15 where short_name = 'guardian';
update zone set min_expansion = 15 where short_name = 'steamfontmts';
update zone set min_expansion = 15 where short_name = 'cryptofshade';
update zone set min_expansion = 15 where short_name = 'dragonscaleb';

update zone set min_expansion = 16 where short_name = 'oldfieldofbone';
update zone set min_expansion = 16 where short_name = 'oldkaesoraa';
update zone set min_expansion = 16 where short_name = 'oldkaesorab';
update zone set min_expansion = 16 where short_name = 'oldkurn';
update zone set min_expansion = 16 where short_name = 'oldkithicor';
update zone set min_expansion = 16 where short_name = 'oldcommons';
update zone set min_expansion = 16 where short_name = 'oldhighpass';
update zone set min_expansion = 16 where short_name = 'thevoida';
update zone set min_expansion = 16 where short_name = 'thevoidb';
update zone set min_expansion = 16 where short_name = 'thevoidc';
update zone set min_expansion = 16 where short_name = 'thevoidd';
update zone set min_expansion = 16 where short_name = 'thevoide';
update zone set min_expansion = 16 where short_name = 'thevoidf';
update zone set min_expansion = 16 where short_name = 'thevoidg';
update zone set min_expansion = 16 where short_name = 'oceangreenhills';
update zone set min_expansion = 16 where short_name = 'oceangreenvillag';
update zone set min_expansion = 16 where short_name = 'oldblackburrow';
update zone set min_expansion = 16 where short_name = 'bertoxtemple';
update zone set min_expansion = 16 where short_name = 'discord';
update zone set min_expansion = 16 where short_name = 'discordtower';
update zone set min_expansion = 16 where short_name = 'oldbloodfield';
update zone set min_expansion = 16 where short_name = 'precipiceofwar';
update zone set min_expansion = 16 where short_name = 'olddranik';
update zone set min_expansion = 16 where short_name = 'toskirakk';
update zone set min_expansion = 16 where short_name = 'korascian';
update zone set min_expansion = 16 where short_name = 'rathechamber';

update zone set min_expansion = 99 where short_name = 'tutorial';
update zone set min_expansion = 99 where short_name = 'load';
update zone set min_expansion = 99 where short_name = 'load2';
update zone set min_expansion = 99 where short_name = 'clz';
update zone set min_expansion = 99 where short_name = 'apprentice';
update zone set min_expansion = 99 where short_name = 'arttest';
update zone set min_expansion = 99 where short_name = 'aviak';
update zone set min_expansion = 99 where short_name = 'befallenb';
update zone set min_expansion = 99 where short_name = 'erudsxing2';
update zone set min_expansion = 99 where short_name = 'highpasskeep';
update zone set min_expansion = 99 where short_name = 'kithforest';
update zone set min_expansion = 99 where short_name = 'nektropos';
update zone set min_expansion = 99 where short_name = 'neriakd';

